insert into products (Name, Category, Price) values ('Asian Noodle Salad Kit', 'Food - Salads', 3157);
insert into products (Name, Category, Price) values ('Puzzle', 'Toys', 4834);
insert into products (Name, Category, Price) values ('Fitness Tracker Watch', 'Wearable Tech', 4226);
insert into products (Name, Category, Price) values ('Noise-Canceling Earbuds', 'Audio', 4842);
insert into products (Name, Category, Price) values ('Ginger Turmeric Latte Mix', 'Food - Beverages', 2899);
insert into products (Name, Category, Price) values ('Phone Case', 'Accessories', 1316);
insert into products (Name, Category, Price) values ('Smart Plug', 'Smart Home', 1435);
insert into products (Name, Category, Price) values ('Cheese Stuffed Jalapenos', 'Food - Snacks', 1723);
insert into products (Name, Category, Price) values ('Ice Cream Maker', 'Kitchen', 4674);
insert into products (Name, Category, Price) values ('Indoor Grill', 'Kitchen', 3877);
insert into products (Name, Category, Price) values ('Maple Almond Butter', 'Food - Nut Butters', 4840);
insert into products (Name, Category, Price) values ('Cinnamon Spiced Almonds', 'Food - Snacks', 2769);
insert into products (Name, Category, Price) values ('Digital Thermostat', 'Home', 3390);
insert into products (Name, Category, Price) values ('Collapsible Camping Cup', 'Outdoor', 2963);
insert into products (Name, Category, Price) values ('Mediterranean Chickpea Bowl', 'Food - Prepared Foods', 2223);
insert into products (Name, Category, Price) values ('Fruit Medley Juice', 'Food - Beverages', 2348);
insert into products (Name, Category, Price) values ('Peach & Mango Salsa', 'Food - Snacks', 4096);
insert into products (Name, Category, Price) values ('Gaming Headset', 'Gaming', 3990);
insert into products (Name, Category, Price) values ('Chili Con Carne Mix', 'Food - Spices & Seasonings', 4936);
insert into products (Name, Category, Price) values ('Frozen Broccoli', 'Food - Frozen', 2490);
insert into products (Name, Category, Price) values ('Pepperoni Pizza Roll-Ups', 'Food - Frozen Foods', 3445);
insert into products (Name, Category, Price) values ('Bluetooth Sleep Headphones', 'Audio', 2736);
insert into products (Name, Category, Price) values ('Woven Storage Baskets', 'Home', 206);
insert into products (Name, Category, Price) values ('Backpack', 'Accessories', 1803);
insert into products (Name, Category, Price) values ('Teriyaki Chicken Bowl', 'Food - Prepared Meals', 2986);
insert into products (Name, Category, Price) values ('Coffee Grinder', 'Kitchen', 2921);
insert into products (Name, Category, Price) values ('Veggie Lovers Pizza', 'Food - Frozen Foods', 1553);
insert into products (Name, Category, Price) values ('Smoked Paprika Chicken Thighs', 'Food - Meat', 2222);
insert into products (Name, Category, Price) values ('Vegetable Pizza Rolls', 'Food - Frozen Foods', 548);
insert into products (Name, Category, Price) values ('Honey', 'Food - Condiments', 1655);
insert into products (Name, Category, Price) values ('Fruit & Nut Trail Mix', 'Food - Snacks', 3325);
insert into products (Name, Category, Price) values ('Balsamic Fig Dressing', 'Food - Condiments', 4830);
insert into products (Name, Category, Price) values ('Board Game', 'Toys', 2221);
insert into products (Name, Category, Price) values ('Weighted Blanket', 'Health', 2114);
insert into products (Name, Category, Price) values ('Puzzle', 'Toys', 4665);
insert into products (Name, Category, Price) values ('Thermostatic Shower Valve Kit', 'Bathroom', 4653);
insert into products (Name, Category, Price) values ('Cat Tree with Scratching Posts', 'Pets', 1799);
insert into products (Name, Category, Price) values ('Elegant Lace Dress', 'Clothing - Dresses', 1565);
insert into products (Name, Category, Price) values ('Pumpkin Spice Granola', 'Food - Breakfast', 3543);
insert into products (Name, Category, Price) values ('Sweet and Sour Sauce', 'Food - Condiments', 3628);
insert into products (Name, Category, Price) values ('Car Vacuum Cleaner', 'Automotive', 890);
insert into products (Name, Category, Price) values ('Garlic Herb Marinade', 'Food - Marinades', 4848);
insert into products (Name, Category, Price) values ('Floral Summer Dress', 'Clothing - Dresses', 4956);
insert into products (Name, Category, Price) values ('Chickpea Salad', 'Food - Prepared Foods', 1555);
insert into products (Name, Category, Price) values ('Quality Chef Apron', 'Kitchen', 2517);
insert into products (Name, Category, Price) values ('Garden Vegetable Soup', 'Food - Canned Goods', 1605);
insert into products (Name, Category, Price) values ('Pineapple Salsa', 'Food - Condiments', 3124);
insert into products (Name, Category, Price) values ('Air Fryer Oven', 'Kitchen', 2575);
insert into products (Name, Category, Price) values ('Workstation Laptop Stand', 'Office', 2217);
insert into products (Name, Category, Price) values ('Sriracha Hot Chili Sauce', 'Food - Condiments', 1963);
