insert into customer (fullName, address, phone, age, gender, password) values ('Toddy Stolli', 'San José Poaquil', '+502 616 951 8332', 87, 'Male', 'Exeter');
insert into customer (fullName, address, phone, age, gender, password) values ('Emelita Sparhawk', 'Paris 08', '+33 612 102 0064', 76, 'Female', 'Lloydminster');
insert into customer (fullName, address, phone, age, gender, password) values ('Barde Cochern', 'Voi', '+254 962 738 6299', 98, 'Male', 'Liège');
insert into customer (fullName, address, phone, age, gender, password) values ('Luciana Mussington', 'Anicuns', '+55 843 820 2975', 66, 'Female', 'Cedar City');
insert into customer (fullName, address, phone, age, gender, password) values ('Bessie Juan', 'Masuda', '+81 819 586 2750', 64, 'Female', 'Kapanga');
insert into customer (fullName, address, phone, age, gender, password) values ('Virgie Eim', 'Shangyu', '+86 363 119 5425', 37, 'Female', 'Wilkes-Barre');
insert into customer (fullName, address, phone, age, gender, password) values ('Gaile Westmerland', 'Penha Longa', '+351 333 500 4807', 66, 'Male', 'Pawe');
insert into customer (fullName, address, phone, age, gender, password) values ('Costa Charman', 'Holguín', '+53 139 959 4165', 42, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Mirabella Rix', 'Shimeitang', '+86 775 337 4326', 58, 'Female', 'Detroit');
insert into customer (fullName, address, phone, age, gender, password) values ('Remington Barajaz', 'Budapest', '+36 918 194 0889', 83, 'Male', 'Concord');
insert into customer (fullName, address, phone, age, gender, password) values ('Luelle Meconi', 'Tsushima', '+81 905 374 6209', 49, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Geoffrey Sharplin', 'Latacunga', '+593 653 434 0498', 51, 'Male', 'Wink');
insert into customer (fullName, address, phone, age, gender, password) values ('Brenna Holehouse', 'Honghe', '+86 365 443 5826', 53, 'Female', 'Bainyik');
insert into customer (fullName, address, phone, age, gender, password) values ('Rafe O'' Hanvey', 'Santo Domingo', '+53 823 770 7695', 26, 'Male', 'Ocaña');
insert into customer (fullName, address, phone, age, gender, password) values ('Demetri Barrand', 'Fusagasuga', '+57 220 167 1193', 96, 'Male', 'Kaoh Kong');
insert into customer (fullName, address, phone, age, gender, password) values ('Alie Wathey', 'Santo Antônio do Içá', '+55 769 540 0828', 64, 'Female', 'Mengomeyén');
insert into customer (fullName, address, phone, age, gender, password) values ('Archibald Brashaw', 'Passos', '+351 553 904 6343', 50, 'Male', 'Ganja');
insert into customer (fullName, address, phone, age, gender, password) values ('Westbrook Glyn', 'Sovetakan', '+374 163 364 6186', 30, 'Male', 'Liboi');
insert into customer (fullName, address, phone, age, gender, password) values ('Ogdon Noel', 'Tajimi', '+81 222 420 6603', 41, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Derron Ludlamme', 'Koksovyy', '+7 711 723 7585', 24, 'Male', 'Kugaaruk');
insert into customer (fullName, address, phone, age, gender, password) values ('Clemens Riding', 'Shangcai Zhongxing', '+86 601 676 0730', 27, 'Male', 'Nadym');
insert into customer (fullName, address, phone, age, gender, password) values ('Kareem Abson', 'Al Hijrah', '+967 410 663 7777', 19, 'Male', 'Caye Chapel');
insert into customer (fullName, address, phone, age, gender, password) values ('Leupold Lathom', 'Englewood', '+1 303 936 4853', 63, 'Male', 'Puerto Putumayo');
insert into customer (fullName, address, phone, age, gender, password) values ('Viole Keyzor', 'Jacutinga', '+55 374 758 2682', 38, 'Female', 'Quijarro');
insert into customer (fullName, address, phone, age, gender, password) values ('Joete Rodolfi', 'Portoviejo', '+593 458 274 2655', 48, 'Female', 'Governador Valadares');
insert into customer (fullName, address, phone, age, gender, password) values ('Tierney Seage', 'Diapaga', '+226 904 374 8281', 33, 'Female', 'Emigrant Gap');
insert into customer (fullName, address, phone, age, gender, password) values ('Isadora Worsom', 'Santo Antônio do Içá', '+55 661 382 9945', 53, 'Female', 'Reconquista');
insert into customer (fullName, address, phone, age, gender, password) values ('Gabby Mannock', 'Mosjøen', '+47 117 344 0298', 47, 'Male', 'Spratley Islands');
insert into customer (fullName, address, phone, age, gender, password) values ('Batholomew Leijs', 'Montpellier', '+33 411 523 6638', 87, 'Male', 'Willmar');
insert into customer (fullName, address, phone, age, gender, password) values ('Orbadiah Stearley', 'Jamaica', '+1 212 759 3968', 54, 'Male', 'Brookings');
insert into customer (fullName, address, phone, age, gender, password) values ('Uri Gromley', 'Salegading', '+62 934 114 9164', 23, 'Male', 'Texarkana');
insert into customer (fullName, address, phone, age, gender, password) values ('Vivi Killiam', 'Pushkin', '+7 507 309 5111', 36, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Hobart Alden', 'Strasbourg', '+33 395 217 7469', 52, 'Male', 'Bobo Dioulasso');
insert into customer (fullName, address, phone, age, gender, password) values ('Sheffie Motten', 'Qal‘ah-ye Fārsī', '+93 230 922 5988', 100, 'Male', 'Arcata/Eureka');
insert into customer (fullName, address, phone, age, gender, password) values ('Tamara Arundel', 'Isiolo', '+254 706 375 3097', 53, 'Female', 'La Grande Rivière');
insert into customer (fullName, address, phone, age, gender, password) values ('Laurie Matten', 'Tokoname', '+81 412 836 5330', 95, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Flory Mc Queen', 'Littleton', '+1 303 492 8891', 62, 'Female', 'Borba');
insert into customer (fullName, address, phone, age, gender, password) values ('Casey Halcro', 'Pragen Selatan', '+62 348 622 9267', 79, 'Male', 'Columbus');
insert into customer (fullName, address, phone, age, gender, password) values ('Mick Condit', 'Horka nad Moravou', '+420 272 585 3231', 31, 'Male', 'Fort Stewart(Hinesville)');
insert into customer (fullName, address, phone, age, gender, password) values ('Wilma Laden', 'Fudian', '+86 899 619 9206', 81, 'Female', 'Karlstad');
insert into customer (fullName, address, phone, age, gender, password) values ('Paulina Rabjohns', 'Plužine', '+382 450 746 7188', 31, 'Female', 'Sisimiut');
insert into customer (fullName, address, phone, age, gender, password) values ('Dennet Sazio', 'Garajati', '+62 364 816 6644', 26, 'Male', 'Neerlerit Inaat');
insert into customer (fullName, address, phone, age, gender, password) values ('Sullivan Gurney', 'Santander', '+34 207 778 1885', 63, 'Male', 'Tres Esquinas');
insert into customer (fullName, address, phone, age, gender, password) values ('Danie Fowls', 'Pancheng', '+86 877 387 5269', 75, 'Male', 'Santo Antônio Do Içá');
insert into customer (fullName, address, phone, age, gender, password) values ('Diarmid MacAskill', 'Dangcalan', '+63 331 994 5425', 57, 'Male', 'Presidente Venceslau');
insert into customer (fullName, address, phone, age, gender, password) values ('Jordan Lampbrecht', 'Dvorichna', '+380 817 873 2414', 54, 'Male', 'Iturup Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Gayleen Casham', 'Krajan', '+62 176 442 3652', 80, 'Female', 'Jakar');
insert into customer (fullName, address, phone, age, gender, password) values ('Loretta Harral', 'Wincrange', '+352 268 445 4418', 26, 'Female', 'Bridgetown');
insert into customer (fullName, address, phone, age, gender, password) values ('Maura Bednell', 'El Ksour', '+216 106 883 1687', 89, 'Female', 'Jinchang');
insert into customer (fullName, address, phone, age, gender, password) values ('Cissiee Heaney', 'Thị Trấn Mường Khương', '+84 134 181 8149', 24, 'Female', 'Salton City');
insert into customer (fullName, address, phone, age, gender, password) values ('Chery Corballis', 'Palmas De Gran Canaria, Las', '+34 767 643 2282', 89, 'Female', 'San Francisco');
insert into customer (fullName, address, phone, age, gender, password) values ('Cathy Gauld', 'Banghai', '+86 976 891 3010', 18, 'Female', 'Zyryanka');
insert into customer (fullName, address, phone, age, gender, password) values ('Tobi Donnellan', 'Khlong Hat', '+66 225 987 7119', 82, 'Female', 'Ivishak River');
insert into customer (fullName, address, phone, age, gender, password) values ('Idalia Colgan', 'Balesari', '+62 976 564 3490', 92, 'Female', 'Aitutaki');
insert into customer (fullName, address, phone, age, gender, password) values ('Corrina Legrand', 'Ar Rawḑah', '+967 225 476 0802', 24, 'Female', 'Long Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Theresina Bowra', 'Illapel', '+56 822 426 9242', 54, 'Female', 'Fresno');
insert into customer (fullName, address, phone, age, gender, password) values ('Andriette MacMaster', 'Goya', '+54 895 299 1628', 89, 'Female', 'Sheep Mountain');
insert into customer (fullName, address, phone, age, gender, password) values ('Beatrisa Rebeiro', 'Ra-ngae', '+66 740 708 9948', 92, 'Female', 'Deputatskiy');
insert into customer (fullName, address, phone, age, gender, password) values ('Ruben Wattins', 'Bacabal', '+55 502 312 0979', 78, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Marlane Hows', 'Shancheng', '+86 868 299 8906', 59, 'Female', 'Arso-Papua Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Robinett Curzon', 'Gia Nghĩa', '+84 524 333 0990', 28, 'Female', 'Morlaix/Ploujean');
insert into customer (fullName, address, phone, age, gender, password) values ('Nancee Pruvost', 'Paris 07', '+33 760 927 6183', 64, 'Female', 'Eureka');
insert into customer (fullName, address, phone, age, gender, password) values ('Leighton Duester', 'Curitibanos', '+55 808 103 5052', 71, 'Male', 'San Diego');
insert into customer (fullName, address, phone, age, gender, password) values ('Quinton Domenc', 'At Tall al Kabīr', '+20 428 994 8060', 35, 'Male', 'Goodyear');
insert into customer (fullName, address, phone, age, gender, password) values ('Ernesta Halston', 'Manhete', '+351 435 103 2113', 84, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Jamey Edlin', 'Lanas', '+63 426 370 1085', 61, 'Male', 'Fort St.John');
insert into customer (fullName, address, phone, age, gender, password) values ('Giffer Fayter', 'Daduo', '+86 640 245 0891', 93, 'Male', 'Tripoli');
insert into customer (fullName, address, phone, age, gender, password) values ('Irita Crossan', 'Tuochuan', '+86 714 300 9715', 69, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Eleen Sprakes', 'Madagali', '+234 981 380 5553', 88, 'Female', 'Woodie Woodie');
insert into customer (fullName, address, phone, age, gender, password) values ('Dukie Kettow', 'Puck', '+48 149 679 4650', 55, 'Male', 'Westhampton Beach');
insert into customer (fullName, address, phone, age, gender, password) values ('Rafferty Turton', 'Tojal', '+351 427 693 3637', 29, 'Male', 'Biloela');
insert into customer (fullName, address, phone, age, gender, password) values ('Kristoffer Dunkirk', 'Santa Lucia', '+63 233 455 2122', 59, 'Male', 'Chaoyang');
insert into customer (fullName, address, phone, age, gender, password) values ('Morganica Markie', 'Calde', '+351 249 652 9098', 71, 'Female', 'Kédougou');
insert into customer (fullName, address, phone, age, gender, password) values ('Courtenay Rodgier', 'Tanjungbatu', '+62 393 774 6240', 33, 'Female', 'Biangabip');
insert into customer (fullName, address, phone, age, gender, password) values ('Kimbell Kirkup', 'Bilicenii Vechi', '+373 757 748 9576', 39, 'Male', 'Semera');
insert into customer (fullName, address, phone, age, gender, password) values ('Vance Curman', 'Troitsk', '+7 653 117 8908', 63, 'Male', 'Kankan');
insert into customer (fullName, address, phone, age, gender, password) values ('Tobias Linham', 'Arjona', '+57 468 161 7260', 33, 'Male', 'Wakaya Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Jasmina Jedrzejczyk', 'Peruc', '+420 226 148 7511', 45, 'Female', 'Elk City');
insert into customer (fullName, address, phone, age, gender, password) values ('Eulalie Sibbert', 'Simpang', '+62 447 135 0560', 66, 'Female', 'Serui-Japen Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Finley Daunay', 'Yiyang', '+86 151 786 2826', 79, 'Male', 'Ji''an');
insert into customer (fullName, address, phone, age, gender, password) values ('Reider Coulthard', 'Santo Antônio de Pádua', '+55 563 128 1368', 26, 'Male', 'Pine Mountain');
insert into customer (fullName, address, phone, age, gender, password) values ('Galen Kornousek', 'Zhouzhuang', '+86 931 682 1696', 79, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Mariya O''Flaherty', 'Guantang', '+86 396 192 1538', 41, 'Female', 'Carlton Hill');
insert into customer (fullName, address, phone, age, gender, password) values ('Violette Putman', 'Dzüünharaa', '+976 625 618 6636', 36, 'Female', 'Nogliki-Sakhalin Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Dominica Penna', 'Ponte', '+351 637 540 3619', 88, 'Female', 'Beckley');
insert into customer (fullName, address, phone, age, gender, password) values ('Rufus Burnett', 'Paarl', '+27 366 517 7021', 30, 'Male', 'Kangerlussuaq');
insert into customer (fullName, address, phone, age, gender, password) values ('Kate Richings', 'Zhuozishan', '+86 920 946 8775', 61, 'Female', 'Parsabad');
insert into customer (fullName, address, phone, age, gender, password) values ('Hunt Ord', 'Takari', '+62 850 124 7584', 42, 'Male', 'Novo Aripuanã');
insert into customer (fullName, address, phone, age, gender, password) values ('Mart Strover', 'Marte', '+234 280 417 8916', 76, 'Male', 'Francisco Beltrão');
insert into customer (fullName, address, phone, age, gender, password) values ('Juliana Battson', 'Jingping', '+86 243 470 9350', 73, 'Female', 'Sovetskaya Gavan');
insert into customer (fullName, address, phone, age, gender, password) values ('Nevins Hender', 'Xinxing', '+86 426 850 1733', 52, 'Male', 'Divinópolis');
insert into customer (fullName, address, phone, age, gender, password) values ('Abdel Gannicott', 'San Fernando', '+63 150 455 3075', 25, 'Male', 'Carepa');
insert into customer (fullName, address, phone, age, gender, password) values ('Bryana Stratten', 'Xiangcunxiang', '+86 734 233 0178', 61, 'Female', 'Kira');
insert into customer (fullName, address, phone, age, gender, password) values ('Woody O''Hearn', 'Montes Claros', '+55 489 797 2603', 54, 'Male', 'Klawock');
insert into customer (fullName, address, phone, age, gender, password) values ('Fallon Litel', 'Vidual', '+351 826 678 9343', 40, 'Female', 'Ziguinchor');
insert into customer (fullName, address, phone, age, gender, password) values ('Maddie Skaif', 'Carahue', '+56 957 177 6036', 58, 'Female', 'La Macarena');
insert into customer (fullName, address, phone, age, gender, password) values ('Noby Gier', 'Gostivar', '+389 864 407 1815', 62, 'Male', 'Osceola');
insert into customer (fullName, address, phone, age, gender, password) values ('Luciano Yitshak', 'Pora', '+62 790 243 1701', 91, 'Male', 'Canberra');
insert into customer (fullName, address, phone, age, gender, password) values ('Jeremy Cockhill', 'Březová', '+420 181 196 8398', 96, 'Male', 'Obano-Papua Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Kipp Pawley', 'Shangdian', '+86 946 423 1408', 80, 'Male', 'Telegraph Creek');
insert into customer (fullName, address, phone, age, gender, password) values ('Sidnee Traske', 'Neftekamsk', '+7 410 295 0328', 39, 'Male', 'Ubari');
insert into customer (fullName, address, phone, age, gender, password) values ('Jocelyn Mirfield', 'Cinunjang', '+62 409 981 7295', 32, 'Female', 'San Pedro Sula');
insert into customer (fullName, address, phone, age, gender, password) values ('Jamie Hum', 'Waiwejak', '+62 321 241 2430', 79, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Junia Kees', 'Cambarus', '+63 705 975 2122', 74, 'Female', 'Cortland');
insert into customer (fullName, address, phone, age, gender, password) values ('Karalee Biasio', 'Talashkino', '+7 629 652 3665', 86, 'Female', 'Hermiston');
insert into customer (fullName, address, phone, age, gender, password) values ('Alleyn Arstingall', 'Bizhou', '+86 923 906 2609', 94, 'Male', 'Myitkyina');
insert into customer (fullName, address, phone, age, gender, password) values ('Giusto Garment', 'Sarata', '+380 774 981 7401', 28, 'Male', 'Bedford');
insert into customer (fullName, address, phone, age, gender, password) values ('Taddeo Baudassi', 'Benhao', '+86 314 770 5029', 34, 'Male', 'Chachapoyas');
insert into customer (fullName, address, phone, age, gender, password) values ('Florance Beckenham', 'Kakan', '+62 281 240 7099', 58, 'Female', 'River Cess');
insert into customer (fullName, address, phone, age, gender, password) values ('Cozmo Lipgens', 'Ngampon', '+62 314 472 3579', 56, 'Male', 'Gabriola Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Tabatha Mizen', 'Redange-sur-Attert', '+352 909 716 1616', 79, 'Female', 'Vunisea');
insert into customer (fullName, address, phone, age, gender, password) values ('Bernadette Macconachy', 'Kario', '+92 637 885 3342', 56, 'Female', 'Fuyuan');
insert into customer (fullName, address, phone, age, gender, password) values ('Nicolea Teers', 'Zorak', '+374 264 261 7592', 38, 'Female', 'Bauru');
insert into customer (fullName, address, phone, age, gender, password) values ('Rakel Hinrichs', 'Chengxiang', '+86 518 368 8193', 100, 'Female', 'Buon Ma Thuot');
insert into customer (fullName, address, phone, age, gender, password) values ('Tye O'' Borne', 'Bayeux', '+55 906 464 7594', 49, 'Male', 'Jacmel');
insert into customer (fullName, address, phone, age, gender, password) values ('Crista Frisel', 'Haukivuori', '+358 194 785 6728', 94, 'Female', 'Villavicencio');
insert into customer (fullName, address, phone, age, gender, password) values ('Carlie Honisch', 'Heishan', '+86 712 328 2271', 63, 'Male', 'Trondheim');
insert into customer (fullName, address, phone, age, gender, password) values ('Brose Nielson', 'Outeiro', '+351 229 755 6727', 79, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Lyn Sleaford', 'Watodei', '+62 431 872 1952', 71, 'Female', 'Tenkodogo');
insert into customer (fullName, address, phone, age, gender, password) values ('Rawley Fawke', 'Wajak', '+62 336 434 5014', 58, 'Male', 'Magangué');
insert into customer (fullName, address, phone, age, gender, password) values ('Marcellus Braniff', 'Mīrpur Māthelo', '+92 701 174 9131', 39, 'Male', 'Cherepovets');
insert into customer (fullName, address, phone, age, gender, password) values ('Gard Rattry', 'Wansheng', '+86 131 682 5109', 60, 'Male', 'Bisbee');
insert into customer (fullName, address, phone, age, gender, password) values ('El Dalston', 'Yanglinshi', '+86 204 619 9095', 100, 'Male', 'Rivière-du-Loup');
insert into customer (fullName, address, phone, age, gender, password) values ('George Giacobini', 'Neringa', '+370 641 930 3603', 80, 'Male', 'Clarksville');
insert into customer (fullName, address, phone, age, gender, password) values ('Timmi Pallaske', 'Santa Cruz Cabrália', '+55 300 510 4172', 64, 'Female', 'Sept-Îles');
insert into customer (fullName, address, phone, age, gender, password) values ('Bendix Ciccoloi', 'Danville', '+1 643 606 8245', 68, 'Male', 'Burbank');
insert into customer (fullName, address, phone, age, gender, password) values ('Mayer Stratford', 'Kupusina', '+381 484 779 8446', 33, 'Male', 'Villa Garzón');
insert into customer (fullName, address, phone, age, gender, password) values ('Teriann Craydon', 'Xuefu', '+86 256 604 2926', 59, 'Female', 'Teraina');
insert into customer (fullName, address, phone, age, gender, password) values ('Mikkel Dines', 'Buurhakaba', '+252 449 157 5412', 20, 'Male', 'Coral Harbour');
insert into customer (fullName, address, phone, age, gender, password) values ('Ulberto Reese', 'Tadine', '+687 671 230 8524', 74, 'Male', 'Seguela');
insert into customer (fullName, address, phone, age, gender, password) values ('Janetta Evered', 'Heitan', '+86 995 247 2066', 92, 'Female', 'Summer Beaver');
insert into customer (fullName, address, phone, age, gender, password) values ('Valaree Shortall', 'Haoping', '+86 186 299 9268', 94, 'Female', 'San Rafael');
insert into customer (fullName, address, phone, age, gender, password) values ('Coralyn Gellan', 'Pescadería', '+1 611 802 4920', 79, 'Female', 'Bălți');
insert into customer (fullName, address, phone, age, gender, password) values ('Heywood Coaten', 'Spas-Klepiki', '+7 994 499 3627', 100, 'Male', 'Lynn Lake');
insert into customer (fullName, address, phone, age, gender, password) values ('Garrett Mudd', 'Wang Nam Khiao', '+66 667 391 6426', 41, 'Male', 'Nassau');
insert into customer (fullName, address, phone, age, gender, password) values ('Mac Beauchop', 'Queenstown', '+27 954 551 0518', 33, 'Male', 'Klerksdorp');
insert into customer (fullName, address, phone, age, gender, password) values ('Kinna Whitbread', 'Zhushan', '+86 990 775 1388', 94, 'Female', 'Simbai');
insert into customer (fullName, address, phone, age, gender, password) values ('Ethe Ellwood', 'Megalochórion', '+30 998 238 7316', 59, 'Male', 'Fargo');
insert into customer (fullName, address, phone, age, gender, password) values ('Antoni Spyer', 'Lopez Jaena', '+63 580 637 0060', 41, 'Male', 'Tau Village');
insert into customer (fullName, address, phone, age, gender, password) values ('Jillene Simes', 'Puerto Rico', '+57 789 863 7198', 85, 'Female', 'Apple Valley');
insert into customer (fullName, address, phone, age, gender, password) values ('Karlee Josifovitz', 'Sōja', '+81 606 713 8166', 60, 'Female', 'Palmas');
insert into customer (fullName, address, phone, age, gender, password) values ('Burl Jedras', 'Zijin', '+86 934 674 0717', 49, 'Male', 'Wilkes-Barre');
insert into customer (fullName, address, phone, age, gender, password) values ('Dianemarie Paniman', 'Raków', '+48 230 349 5027', 65, 'Female', 'Les Saintes');
insert into customer (fullName, address, phone, age, gender, password) values ('Olvan Fitzpayn', 'Khuzdār', '+92 163 509 1207', 74, 'Male', 'Auburn');
insert into customer (fullName, address, phone, age, gender, password) values ('Nessy Whitwham', 'Perzów', '+48 616 148 1954', 25, 'Female', 'Saint Anne');
insert into customer (fullName, address, phone, age, gender, password) values ('Halley Leyband', 'El Real', '+58 979 470 1236', 90, 'Female', 'Zaragoza');
insert into customer (fullName, address, phone, age, gender, password) values ('Hobie Deam', 'Pridonskoy', '+7 532 237 1632', 62, 'Male', 'Oshkosh');
insert into customer (fullName, address, phone, age, gender, password) values ('Katharyn Spring', 'Xianghu', '+86 413 843 8894', 42, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Ettie Doddemeede', 'Taquara', '+55 147 338 9700', 54, 'Female', 'Kamusi');
insert into customer (fullName, address, phone, age, gender, password) values ('Adrian Ireson', 'Baoquanshan', '+86 198 102 0366', 87, 'Male', 'Kamulai Mission');
insert into customer (fullName, address, phone, age, gender, password) values ('Meris Maryman', 'Fresnes', '+33 371 283 5567', 41, 'Female', 'Brochet');
insert into customer (fullName, address, phone, age, gender, password) values ('Frazer Bernardo', 'Qingshui', '+86 252 632 2462', 43, 'Male', 'Lalibela');
insert into customer (fullName, address, phone, age, gender, password) values ('Maurise Lembrick', 'Łęki Szlacheckie', '+48 894 487 8198', 94, 'Female', 'Araguaiana');
insert into customer (fullName, address, phone, age, gender, password) values ('Casey Hazart', 'Tanshan', '+86 533 124 9323', 45, 'Female', 'Key Largo');
insert into customer (fullName, address, phone, age, gender, password) values ('Trix Colquite', 'Bremen', '+49 827 188 9992', 72, 'Female', 'Mazatlán');
insert into customer (fullName, address, phone, age, gender, password) values ('Berenice Flarity', 'Vila', '+351 964 384 3118', 33, 'Female', 'Pucon');
insert into customer (fullName, address, phone, age, gender, password) values ('Britni Vasse', 'Uluale', '+62 615 163 8455', 59, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Susi Annesley', 'Stockholm', '+46 807 452 9024', 93, 'Female', 'Corinth');
insert into customer (fullName, address, phone, age, gender, password) values ('Glenn Pinck', 'Barrouallie', '+1 252 436 3829', 41, 'Male', 'Freetown');
insert into customer (fullName, address, phone, age, gender, password) values ('Roderigo Reedshaw', 'Radlje ob Dravi', '+386 571 632 3315', 20, 'Male', 'Lawrenceville');
insert into customer (fullName, address, phone, age, gender, password) values ('Beret Canero', 'Dianzi', '+86 955 862 2678', 76, 'Female', 'Kenora');
insert into customer (fullName, address, phone, age, gender, password) values ('Kelcy Kobelt', 'Sakule', '+381 367 150 2134', 38, 'Female', 'Kuito');
insert into customer (fullName, address, phone, age, gender, password) values ('Codee Cranmer', 'Murtajih', '+62 806 105 0666', 47, 'Female', 'Charlotte');
insert into customer (fullName, address, phone, age, gender, password) values ('Florencia Birtwell', 'Palocabildo', '+57 393 945 4879', 82, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Fremont Loveday', 'Portelândia', '+55 826 708 1261', 59, 'Male', 'Odessa');
insert into customer (fullName, address, phone, age, gender, password) values ('Valentine Rubinovici', 'Nangela', '+62 379 494 9182', 97, 'Male', 'Lese');
insert into customer (fullName, address, phone, age, gender, password) values ('Winifield O''Lennane', 'Salfīt', '+970 767 942 8581', 27, 'Male', 'Hatchet Lake');
insert into customer (fullName, address, phone, age, gender, password) values ('Lucina Hallbird', 'Duozhu', '+86 396 548 0380', 21, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Edgardo Floyd', 'Wilmington', '+1 302 422 9082', 58, 'Male', 'Dorobisoro');
insert into customer (fullName, address, phone, age, gender, password) values ('Myrlene Limeburner', 'Jadho', '+62 419 499 2210', 85, 'Female', 'Freetown');
insert into customer (fullName, address, phone, age, gender, password) values ('Waverly Schimek', 'Rochester', '+1 585 810 6984', 96, 'Male', 'Le Havre/Octeville');
insert into customer (fullName, address, phone, age, gender, password) values ('Creight Torrie', 'Beskolen', '+62 512 340 5403', 24, 'Male', 'Kolombangara Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Rosaleen Parslow', 'Charenton-le-Pont', '+33 654 166 5616', 49, 'Female', 'Terre Haute');
insert into customer (fullName, address, phone, age, gender, password) values ('Glynda Woollacott', 'Vysokogornyy', '+7 151 977 2273', 87, 'Female', 'Mangochi');
insert into customer (fullName, address, phone, age, gender, password) values ('Alessandro Orae', 'Popovice', '+420 223 399 2212', 18, 'Male', 'Stuart');
insert into customer (fullName, address, phone, age, gender, password) values ('Filberto Pougher', 'Bulupayung', '+62 614 809 6057', 26, 'Male', 'Cresswell Downs');
insert into customer (fullName, address, phone, age, gender, password) values ('Callean Robillard', 'Dzhetygara', '+7 704 422 6132', 45, 'Male', 'Flensburg');
insert into customer (fullName, address, phone, age, gender, password) values ('Pat Avann', 'Khilok', '+7 176 442 4911', 29, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Fabien Berns', 'Górki', '+48 464 202 0207', 96, 'Male', 'Gary');
insert into customer (fullName, address, phone, age, gender, password) values ('Evin Pepler', 'Dachong', '+86 238 546 8101', 63, 'Male', 'Rogers');
insert into customer (fullName, address, phone, age, gender, password) values ('Janos Silman', 'Limoges', '+33 641 282 3477', 20, 'Male', 'Huslia');
insert into customer (fullName, address, phone, age, gender, password) values ('Jessica Simister', 'Santa Lucía', '+504 617 464 1265', 68, 'Female', 'Ōzora');
insert into customer (fullName, address, phone, age, gender, password) values ('Corena Greenley', 'Olenegorsk', '+7 387 247 9710', 59, 'Female', 'Juiz De Fora');
insert into customer (fullName, address, phone, age, gender, password) values ('Sissie Elliker', 'Dole', '+33 458 495 5188', 44, 'Female', 'Tessenei');
insert into customer (fullName, address, phone, age, gender, password) values ('Moina Warnes', 'Suqu', '+86 409 369 9697', 56, 'Female', 'Kalaleh');
insert into customer (fullName, address, phone, age, gender, password) values ('Sissie Donaghie', 'Il’inskiy Pogost', '+7 781 311 4809', 36, 'Female', 'Warder');
insert into customer (fullName, address, phone, age, gender, password) values ('Bartholomeus Zarb', 'Monte Patria', '+56 864 121 7038', 86, 'Male', 'Casiguran');
insert into customer (fullName, address, phone, age, gender, password) values ('Hube Scoffins', 'Jialu', '+86 690 632 2426', 40, 'Male', 'Moa');
insert into customer (fullName, address, phone, age, gender, password) values ('Garvin Benting', 'Glan', '+63 172 402 4302', 82, 'Male', 'Valledupar');
insert into customer (fullName, address, phone, age, gender, password) values ('Leslie Kleisle', 'Huangling', '+86 622 277 0512', 49, 'Male', 'Kazan');
insert into customer (fullName, address, phone, age, gender, password) values ('Quinn Macia', 'Carolina', '+57 561 131 6892', 55, 'Male', 'Blenheim');
insert into customer (fullName, address, phone, age, gender, password) values ('Dev Tankus', 'Longzhong', '+86 910 302 8877', 94, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Anetta Cullinan', 'Candelaria', '+57 741 496 2599', 74, 'Female', 'Rio Grande');
insert into customer (fullName, address, phone, age, gender, password) values ('Ryley Beccles', 'Badung', '+62 851 575 5062', 45, 'Male', 'Kingston');
insert into customer (fullName, address, phone, age, gender, password) values ('Towny Trunchion', 'Bernay', '+33 122 162 8621', 56, 'Male', 'Novy Urengoy');
insert into customer (fullName, address, phone, age, gender, password) values ('Brander Allnutt', 'Hedi', '+86 418 892 3292', 55, 'Male', 'Praia');
insert into customer (fullName, address, phone, age, gender, password) values ('Perl Lambourne', 'Krimpen aan den IJssel', '+31 945 778 9747', 99, 'Female', 'Manzanillo');
insert into customer (fullName, address, phone, age, gender, password) values ('Murielle Andrivot', 'Maiyema', '+234 701 879 5075', 48, 'Female', 'Koyukuk');
insert into customer (fullName, address, phone, age, gender, password) values ('Antonin Water', 'Vynohradivka', '+380 176 407 5876', 56, 'Male', 'Kangiqsujuaq');
insert into customer (fullName, address, phone, age, gender, password) values ('Danika Akhurst', 'Banjarkemuning', '+62 252 567 9629', 96, 'Female', 'Kemi / Tornio');
insert into customer (fullName, address, phone, age, gender, password) values ('Hedwiga Van den Broek', 'Eláteia', '+30 213 233 7688', 65, 'Female', 'Benguela');
insert into customer (fullName, address, phone, age, gender, password) values ('Vasili Berends', 'Pampas', '+51 759 820 0639', 91, 'Male', 'Alor Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Philip Ferry', 'Amos', '+1 471 502 8653', 56, 'Male', 'Mbatiri');
insert into customer (fullName, address, phone, age, gender, password) values ('Hermina Drake', 'Punkaharju', '+358 293 106 7178', 67, 'Female', 'New York');
insert into customer (fullName, address, phone, age, gender, password) values ('Si Orneblow', 'Pasarkuok', '+62 993 681 5301', 24, 'Male', 'Santiago de Compostela');
insert into customer (fullName, address, phone, age, gender, password) values ('Leanor Critchard', 'Nowy Staw', '+48 515 260 0089', 76, 'Female', 'Sta Cruz de la Palma, La Palma Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Marcie Dalman', 'Cimanggu', '+62 208 439 8311', 82, 'Female', 'St Joseph');
insert into customer (fullName, address, phone, age, gender, password) values ('Davide Trunkfield', 'Hajeom', '+82 965 213 2388', 33, 'Male', 'Ayolas');
insert into customer (fullName, address, phone, age, gender, password) values ('Edd Stemp', 'Sufang', '+86 699 693 6001', 82, 'Male', 'Grand Cess');
insert into customer (fullName, address, phone, age, gender, password) values ('Brigitte Hatwell', 'Jomboy', '+998 457 777 6399', 88, 'Female', 'Lebak');
insert into customer (fullName, address, phone, age, gender, password) values ('Jorgan Hallick', 'Kendalngupuk', '+62 185 962 4334', 65, 'Male', 'Scammon Bay');
insert into customer (fullName, address, phone, age, gender, password) values ('Trev Shera', 'Anshan', '+86 655 166 9857', 25, 'Male', 'Sapir');
insert into customer (fullName, address, phone, age, gender, password) values ('Ashely Rootham', 'Seropédica', '+55 332 665 8051', 23, 'Female', 'Sparti');
insert into customer (fullName, address, phone, age, gender, password) values ('Roanna Unthank', 'Mehmand Chak', '+92 510 176 6369', 99, 'Female', 'Castro');
insert into customer (fullName, address, phone, age, gender, password) values ('Yevette Bunch', 'Sampaio', '+351 315 115 9217', 22, 'Female', 'Bluefield');
insert into customer (fullName, address, phone, age, gender, password) values ('Creight Urian', 'Langsepan', '+62 577 795 8326', 18, 'Male', 'Beaufort');
insert into customer (fullName, address, phone, age, gender, password) values ('Jamaal Aldam', 'San Francisco de Yare', '+58 916 761 2919', 28, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Bern Boscott', 'Zhukeng', '+86 244 941 1642', 68, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Jeri Itzkovich', 'Karajeun', '+62 169 629 9430', 85, 'Female', 'Shirdi');
insert into customer (fullName, address, phone, age, gender, password) values ('Johannes Giraudot', 'Pop', '+998 586 274 7412', 18, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Ferguson Scrymgeour', 'Rio Brilhante', '+55 240 859 7317', 85, 'Male', 'El Dorado');
insert into customer (fullName, address, phone, age, gender, password) values ('Ashton Gaitone', 'Seixezelo', '+351 103 752 6483', 91, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Barrie MacAdam', 'Nizhnekamsk', '+7 338 642 7372', 51, 'Male', 'Fort Pierce');
insert into customer (fullName, address, phone, age, gender, password) values ('Myra Larmor', 'Bayt Ta‘mar', '+970 965 345 8208', 26, 'Female', 'Akulivik');
insert into customer (fullName, address, phone, age, gender, password) values ('Buck O''Hanley', 'Mentougou', '+86 598 582 3140', 92, 'Male', 'Curitiba');
insert into customer (fullName, address, phone, age, gender, password) values ('Rog Norster', 'Mỹ Thọ', '+84 379 570 5305', 25, 'Male', 'Apucarana');
insert into customer (fullName, address, phone, age, gender, password) values ('Tracy Serle', 'Man', '+225 290 591 6053', 60, 'Male', 'Adrian');
insert into customer (fullName, address, phone, age, gender, password) values ('Lianne Wythe', 'Jiaxing', '+86 157 538 6695', 54, 'Female', 'Plovdiv');
insert into customer (fullName, address, phone, age, gender, password) values ('Eleanor Martynikhin', 'Shinan', '+86 488 710 1380', 37, 'Female', 'Concord');
insert into customer (fullName, address, phone, age, gender, password) values ('Roana Andre', 'Watuka', '+62 910 961 4110', 40, 'Female', 'Lappeenranta');
insert into customer (fullName, address, phone, age, gender, password) values ('Maximo Rowlands', 'Gaotan', '+86 975 321 0302', 26, 'Male', 'Silistra');
insert into customer (fullName, address, phone, age, gender, password) values ('Kassey Baldcock', 'Maoping', '+86 388 346 7521', 63, 'Female', 'Terapo Mission');
insert into customer (fullName, address, phone, age, gender, password) values ('Darnell Heppner', 'Maubara', '+670 440 926 1930', 40, 'Male', 'Bongor');
insert into customer (fullName, address, phone, age, gender, password) values ('Ibrahim Atherton', 'Idvor', '+381 491 885 0860', 73, 'Male', 'Owando');
insert into customer (fullName, address, phone, age, gender, password) values ('Michaella Hakes', 'Iida', '+81 328 164 7699', 92, 'Female', 'Decimomannu');
insert into customer (fullName, address, phone, age, gender, password) values ('Eleonora Mollin', 'Pokrovka', '+7 337 985 1856', 92, 'Female', 'Torp');
insert into customer (fullName, address, phone, age, gender, password) values ('Leshia Cosyns', 'Mulchén', '+56 454 525 5107', 73, 'Female', 'Thompson');
insert into customer (fullName, address, phone, age, gender, password) values ('Nelle Hance', 'Gaur', '+977 375 140 9120', 85, 'Female', 'Sapir');
insert into customer (fullName, address, phone, age, gender, password) values ('Hunfredo Eaden', 'Pindi Bhattiān', '+92 898 977 5328', 40, 'Male', 'Clarksburg');
insert into customer (fullName, address, phone, age, gender, password) values ('Haley Caudle', 'Puente Alto', '+56 771 309 6049', 82, 'Male', 'Wausau');
insert into customer (fullName, address, phone, age, gender, password) values ('Loretta Wheatley', 'Turbo', '+57 697 114 5372', 68, 'Female', 'Hibbing');
insert into customer (fullName, address, phone, age, gender, password) values ('Brianna Bisp', 'Acandí', '+57 557 590 2920', 98, 'Female', 'Singleton');
insert into customer (fullName, address, phone, age, gender, password) values ('Austen Adamsky', 'Yong’an', '+86 562 370 2976', 37, 'Male', 'Edmonton');
insert into customer (fullName, address, phone, age, gender, password) values ('Sherm Lengthorn', 'Nandaime', '+505 780 653 4599', 40, 'Male', 'Long Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Fremont Coleford', 'Henglishan', '+86 886 506 3913', 65, 'Male', 'Landivisiau');
insert into customer (fullName, address, phone, age, gender, password) values ('Auria Luno', 'Antaparco', '+51 694 787 5063', 28, 'Female', 'Singapore');
insert into customer (fullName, address, phone, age, gender, password) values ('Glyn Culy', 'Dongen', '+31 766 378 7179', 63, 'Male', 'Livingstone');
insert into customer (fullName, address, phone, age, gender, password) values ('Kirsti Strother', 'Qalqīlyah', '+970 217 391 8798', 23, 'Female', 'Hill City');
insert into customer (fullName, address, phone, age, gender, password) values ('Bevin Matuszak', 'Taochuan', '+86 381 702 7854', 68, 'Male', 'Kelsey');
insert into customer (fullName, address, phone, age, gender, password) values ('Gauthier Petrovsky', 'Helsingborg', '+46 749 360 0683', 22, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Nadya Ehlerding', 'Washington', '+1 202 771 6341', 47, 'Female', 'Kastamonu');
insert into customer (fullName, address, phone, age, gender, password) values ('Stevena Bottom', 'Köln', '+49 896 411 6200', 80, 'Female', 'Pasni');
insert into customer (fullName, address, phone, age, gender, password) values ('Emmaline Yannikov', 'As Suwaydā’', '+963 377 505 1040', 30, 'Female', 'Tampere / Pirkkala');
insert into customer (fullName, address, phone, age, gender, password) values ('Trip Dumphries', 'Sémé', '+221 330 281 8353', 66, 'Male', 'Andros Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Hakeem MacTavish', 'Washington', '+1 202 306 0137', 56, 'Male', 'Claremont');
insert into customer (fullName, address, phone, age, gender, password) values ('Ruthanne Ragles', 'Shuanghe', '+86 153 805 9886', 22, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Mac Zimmerman', 'Maji', '+86 177 115 5026', 51, 'Male', 'Madison');
insert into customer (fullName, address, phone, age, gender, password) values ('Kassey Lyptrit', 'Twyford', '+44 861 566 2429', 91, 'Female', 'Meknes');
insert into customer (fullName, address, phone, age, gender, password) values ('Andrei Mattioli', 'Khao Yoi', '+66 448 568 9029', 40, 'Female', 'Santana Ramos');
insert into customer (fullName, address, phone, age, gender, password) values ('Johnette Collymore', 'Nixi', '+86 445 216 7485', 47, 'Female', 'Repulse Bay');
insert into customer (fullName, address, phone, age, gender, password) values ('Quintina McClifferty', 'Shalazhi', '+7 470 476 0701', 83, 'Female', 'Beica');
insert into customer (fullName, address, phone, age, gender, password) values ('Elaine Catterick', 'Ludvika', '+46 621 326 4892', 50, 'Female', 'Nizhnevartovsk');
insert into customer (fullName, address, phone, age, gender, password) values ('Ailene Ridolfo', 'Baykalovo', '+7 660 481 6631', 69, 'Female', 'Bambu');
insert into customer (fullName, address, phone, age, gender, password) values ('Myles Drohane', 'Lakbok', '+62 688 167 3624', 83, 'Male', 'Mumias');
insert into customer (fullName, address, phone, age, gender, password) values ('Ruddie Tarren', 'La Cumbre', '+57 114 705 4969', 30, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Hunter Boller', 'Huangsha', '+86 983 187 0909', 59, 'Male', 'Fort Resolution');
insert into customer (fullName, address, phone, age, gender, password) values ('Kittie Bingall', 'Marne-la-Vallée', '+33 261 438 9944', 37, 'Female', 'Mount Hagen');
insert into customer (fullName, address, phone, age, gender, password) values ('Minnnie Browell', 'Santol', '+63 882 334 1051', 64, 'Female', 'Laurie River');
insert into customer (fullName, address, phone, age, gender, password) values ('Siward Uff', 'Wedoro', '+62 425 599 6273', 90, 'Male', 'Naiu Atoll');
insert into customer (fullName, address, phone, age, gender, password) values ('Sutherland MacKowle', 'Roriz', '+351 305 988 6263', 98, 'Male', 'Arno Atoll');
insert into customer (fullName, address, phone, age, gender, password) values ('Rhody Pawfoot', 'Bourg-en-Bresse', '+33 335 399 3984', 34, 'Female', 'Nadym');
insert into customer (fullName, address, phone, age, gender, password) values ('Kara-lynn Sykes', 'Grebenskaya', '+7 247 718 6467', 41, 'Female', 'Ankara');
insert into customer (fullName, address, phone, age, gender, password) values ('Titus Gosnoll', 'Paranapanema', '+55 263 904 6096', 56, 'Male', 'Inis Mór');
insert into customer (fullName, address, phone, age, gender, password) values ('Arley Pereira', 'Phuthaditjhaba', '+27 716 191 2641', 44, 'Male', 'Sidi Barrani');
insert into customer (fullName, address, phone, age, gender, password) values ('Cullie Partrick', 'Pigcawayan', '+63 422 441 0707', 77, 'Male', 'Cheongju');
insert into customer (fullName, address, phone, age, gender, password) values ('Adrien Boscott', 'Dorogobuzh', '+7 256 428 1480', 42, 'Male', 'Trier');
insert into customer (fullName, address, phone, age, gender, password) values ('Brana Longfut', 'Artémida', '+30 874 944 1108', 83, 'Female', 'Karluk Lake');
insert into customer (fullName, address, phone, age, gender, password) values ('Miof mela Assad', 'Kaeng Khro', '+66 244 739 7399', 45, 'Female', 'Hartford');
insert into customer (fullName, address, phone, age, gender, password) values ('Meredith Possek', 'Vilcún', '+56 325 907 5494', 48, 'Male', 'Sandy Lake');
insert into customer (fullName, address, phone, age, gender, password) values ('Robinet Nealy', 'Gongju', '+82 356 479 6553', 85, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Sybila Betteriss', 'Leiden', '+31 170 968 2984', 62, 'Female', 'Ord River');
insert into customer (fullName, address, phone, age, gender, password) values ('Thorvald Jeffcoat', 'Sorang', '+7 650 876 4842', 62, 'Male', 'Flat');
insert into customer (fullName, address, phone, age, gender, password) values ('Stirling MacGruer', 'Uddevalla', '+46 840 852 6050', 97, 'Male', 'Khartoum');
insert into customer (fullName, address, phone, age, gender, password) values ('Petronia Vaan', 'San José de Colinas', '+504 255 103 1136', 68, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Urson Taysbil', 'Monjas', '+502 975 640 6270', 65, 'Male', 'Norfolk');
insert into customer (fullName, address, phone, age, gender, password) values ('Glad Carnock', 'Bhunya', '+268 673 220 0660', 83, 'Female', 'Illaga-Papua Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Harland Ramm', 'Kuala Lumpur', '+60 648 705 0516', 25, 'Male', 'Fishers Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Caresse Lamps', 'Dobryatino', '+7 170 163 8491', 48, 'Female', 'Motswari Private Game Reserve');
insert into customer (fullName, address, phone, age, gender, password) values ('Iggy Carefull', 'Domalanoan', '+63 109 782 0325', 49, 'Male', 'Awaba');
insert into customer (fullName, address, phone, age, gender, password) values ('Eula Nance', 'Aomori Shi', '+81 262 747 1646', 20, 'Female', 'Big Rapids');
insert into customer (fullName, address, phone, age, gender, password) values ('Doralia Maggi', 'Jayyūs', '+970 923 809 3699', 52, 'Female', 'Haiphong');
insert into customer (fullName, address, phone, age, gender, password) values ('Kaila Shropsheir', 'Jishan', '+86 800 780 4836', 74, 'Female', 'Richards Bay');
insert into customer (fullName, address, phone, age, gender, password) values ('Cheslie Pudney', 'Peras Ruivas', '+351 102 952 0438', 24, 'Female', 'Bulgan');
insert into customer (fullName, address, phone, age, gender, password) values ('Kalie Hackney', 'Kromy', '+7 812 747 4676', 49, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Romy Fray', 'Antioquia', '+57 335 130 2966', 82, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Jewell McRory', 'Firminy', '+33 881 495 2953', 57, 'Female', 'Yorkton');
insert into customer (fullName, address, phone, age, gender, password) values ('Flinn Iacovo', 'Ivanivka', '+380 502 692 1652', 92, 'Male', 'Banjul');
insert into customer (fullName, address, phone, age, gender, password) values ('Maurita Munkley', 'Solnechnyy', '+7 338 884 2373', 77, 'Female', 'Dubrovnik');
insert into customer (fullName, address, phone, age, gender, password) values ('Leola Roll', 'Wuluo', '+86 586 431 1741', 30, 'Female', 'Hoedspruit');
insert into customer (fullName, address, phone, age, gender, password) values ('Stephen Chamberlaine', 'Xushangqiao', '+86 307 318 0091', 98, 'Male', 'Murray Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Robbyn Davidescu', 'Lutian', '+86 740 563 7143', 68, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Tomi Rizzetti', 'Yolöten', '+993 780 417 3758', 94, 'Female', 'Karratha');
insert into customer (fullName, address, phone, age, gender, password) values ('Christan MacConnell', 'Alquerubim', '+351 498 633 4983', 74, 'Female', 'Round Lake');
insert into customer (fullName, address, phone, age, gender, password) values ('Cleo Maplesden', 'Dongxin', '+86 271 810 7632', 93, 'Female', 'Araçatuba');
insert into customer (fullName, address, phone, age, gender, password) values ('Nate Briar', 'Seaton', '+44 752 899 9963', 99, 'Male', 'Hamadan');
insert into customer (fullName, address, phone, age, gender, password) values ('Damien Thecham', 'Warsaw', '+48 211 690 3538', 22, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Ronny Stinson', 'Matsutō', '+81 830 952 6608', 79, 'Male', 'Puvirnituq');
insert into customer (fullName, address, phone, age, gender, password) values ('Leonerd Dosdale', 'Caigangan', '+63 181 181 8287', 58, 'Male', 'Omitama');
insert into customer (fullName, address, phone, age, gender, password) values ('Francine Bushel', 'Jataí', '+55 528 412 7561', 63, 'Female', 'Amderma');
insert into customer (fullName, address, phone, age, gender, password) values ('Carmine Emes', 'Guintubhan', '+63 262 216 9300', 72, 'Female', 'Fort Leonard Wood');
insert into customer (fullName, address, phone, age, gender, password) values ('Joannes Farlam', 'Lincuo', '+86 551 814 5810', 49, 'Female', 'Izu Oshima');
insert into customer (fullName, address, phone, age, gender, password) values ('Madelyn Scougall', 'Thị Trấn Quảng Uyên', '+84 294 213 0286', 29, 'Female', 'Espinosa');
insert into customer (fullName, address, phone, age, gender, password) values ('Anselma Halfacre', 'Sifangxi', '+86 216 415 1292', 58, 'Female', 'Neiva');
insert into customer (fullName, address, phone, age, gender, password) values ('Barby Osinin', 'Gongping', '+86 673 422 3185', 59, 'Female', 'Mccarthy');
insert into customer (fullName, address, phone, age, gender, password) values ('Kizzee O'' Bee', 'Karadaglije', '+387 114 406 8463', 55, 'Female', 'Bujumbura');
insert into customer (fullName, address, phone, age, gender, password) values ('Farrah Elverstone', 'Olival', '+351 108 769 1480', 38, 'Female', 'Guangyuan');
insert into customer (fullName, address, phone, age, gender, password) values ('Page Craney', 'Dagur', '+86 125 258 8922', 55, 'Female', 'Christiansted St Croix');
insert into customer (fullName, address, phone, age, gender, password) values ('Lanita Fermor', 'Hwange', '+263 618 977 6446', 66, 'Female', 'Golfito');
insert into customer (fullName, address, phone, age, gender, password) values ('Connie Gerard', 'Izhmorskiy', '+7 549 339 0412', 47, 'Male', 'Dayton');
insert into customer (fullName, address, phone, age, gender, password) values ('Babb Illem', 'Mella', '+1 766 929 4025', 47, 'Female', 'Kapit');
insert into customer (fullName, address, phone, age, gender, password) values ('Rubin Ingyon', 'Chengdong', '+86 718 579 0959', 76, 'Male', 'Bomai');
insert into customer (fullName, address, phone, age, gender, password) values ('Adda Castellan', 'Tomakomai', '+81 153 518 1469', 56, 'Female', 'Alluitsup Paa');
insert into customer (fullName, address, phone, age, gender, password) values ('Margi Mabb', 'Međa', '+381 165 111 3349', 96, 'Female', 'Fort Richardson(Anchorage)');
insert into customer (fullName, address, phone, age, gender, password) values ('Xenos Olivas', 'Listvyanskiy', '+7 618 743 8097', 49, 'Male', 'Semporna');
insert into customer (fullName, address, phone, age, gender, password) values ('Rudolf Prescott', 'Öldziyt', '+976 504 624 8004', 83, 'Male', 'Kiwai Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Josephina Troke', 'Muarapinang', '+62 346 268 8377', 43, 'Female', 'Rosh Pina');
insert into customer (fullName, address, phone, age, gender, password) values ('Chevalier Mannion', 'Curug', '+62 708 290 0001', 60, 'Male', 'Biratnagar');
insert into customer (fullName, address, phone, age, gender, password) values ('Annnora Hocking', 'Longka', '+62 489 450 9610', 24, 'Female', 'Malta');
insert into customer (fullName, address, phone, age, gender, password) values ('Lyndsey Ayshford', 'Tongchuan', '+86 307 222 0805', 43, 'Female', 'Aumo');
insert into customer (fullName, address, phone, age, gender, password) values ('Emalia Darleston', 'Bologoye', '+7 876 297 1001', 31, 'Female', 'Bucharest');
insert into customer (fullName, address, phone, age, gender, password) values ('Jannel Gillibrand', 'Biên Hòa', '+84 488 931 2891', 49, 'Female', 'Deer Lake');
insert into customer (fullName, address, phone, age, gender, password) values ('Ulberto Macklam', 'Wangon', '+62 669 749 2159', 19, 'Male', 'Beica');
insert into customer (fullName, address, phone, age, gender, password) values ('Gratiana Buckwell', 'Xushangqiao', '+86 561 817 4458', 84, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Barrett Kale', 'Shuanggang', '+86 224 144 4297', 100, 'Male', 'Kingfisher Lake');
insert into customer (fullName, address, phone, age, gender, password) values ('Lisbeth Jochens', 'Victoria', '+63 832 944 6491', 29, 'Female', 'Tarakan Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Car Papa', 'Vårgårda', '+46 427 394 7383', 79, 'Male', 'Surgut');
insert into customer (fullName, address, phone, age, gender, password) values ('Abraham Gossage', 'Bangued', '+63 823 367 7960', 63, 'Male', 'Morobe');
insert into customer (fullName, address, phone, age, gender, password) values ('Darla Stadding', 'Charlesland', '+353 759 873 2505', 75, 'Female', 'Lac La Biche');
insert into customer (fullName, address, phone, age, gender, password) values ('Kennie Ciobotaro', 'Huntington', '+1 304 244 7793', 89, 'Male', 'Kittilä');
insert into customer (fullName, address, phone, age, gender, password) values ('Wilow Boich', 'Pag-asa', '+63 274 522 1261', 90, 'Female', 'Moyo');
insert into customer (fullName, address, phone, age, gender, password) values ('Vinson Abrashkin', 'Ningyang', '+86 349 859 8690', 30, 'Male', 'Dunk Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Danit Habbin', 'Ash Shafā', '+966 541 920 4239', 42, 'Female', 'Beirut');
insert into customer (fullName, address, phone, age, gender, password) values ('Valentina Keneford', 'Tangga’an', '+86 302 682 8850', 26, 'Female', 'Riberalta');
insert into customer (fullName, address, phone, age, gender, password) values ('Gilbertina De Freitas', 'Yakymivka', '+380 475 456 5854', 89, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Bud Ambrus', 'Isfara', '+992 481 507 7325', 46, 'Male', 'Paonia');
insert into customer (fullName, address, phone, age, gender, password) values ('Perren Sutherland', 'Priekule', '+371 535 485 7005', 23, 'Male', 'Jinan');
insert into customer (fullName, address, phone, age, gender, password) values ('Noelani Kleinstern', 'Saint John', '+356 470 912 3932', 29, 'Female', 'São Gabriel Da Cachoeira');
insert into customer (fullName, address, phone, age, gender, password) values ('Lilith Jado', 'Yanggu', '+86 742 521 2328', 73, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Federica Verillo', 'Marne-la-Vallée', '+33 715 823 1491', 65, 'Female', 'Salisbury');
insert into customer (fullName, address, phone, age, gender, password) values ('Ashien Instock', 'Filothéi', '+30 862 385 0750', 91, 'Female', 'Kalabo');
insert into customer (fullName, address, phone, age, gender, password) values ('Tonnie Crimes', 'Fershampenuaz', '+7 593 464 6274', 88, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Derron Baudino', 'San Pedro Ayampuc', '+502 517 244 3662', 87, 'Male', 'Yangambi');
insert into customer (fullName, address, phone, age, gender, password) values ('Chas Valti', 'Shushi', '+994 826 129 8038', 81, 'Male', 'Kato');
insert into customer (fullName, address, phone, age, gender, password) values ('Galen Coggin', 'Shiqiaotou', '+86 448 898 4695', 89, 'Male', 'Santiago');
insert into customer (fullName, address, phone, age, gender, password) values ('Kassey Rispine', 'Huacrachuco', '+51 891 710 1267', 54, 'Female', 'Akrotiri');
insert into customer (fullName, address, phone, age, gender, password) values ('Pete Yapp', 'Orleans', '+55 933 454 8025', 47, 'Male', 'Wellington');
insert into customer (fullName, address, phone, age, gender, password) values ('Guillermo Renton', 'Kyurdarmir', '+994 799 233 0083', 73, 'Male', 'Kongolo');
insert into customer (fullName, address, phone, age, gender, password) values ('Ninetta Bampkin', 'Lac du Bonnet', '+1 105 551 6647', 47, 'Female', 'Santa Cruz/Graciosa Bay/Luova');
insert into customer (fullName, address, phone, age, gender, password) values ('Rubia Palomba', 'Walakeri', '+62 640 946 7346', 83, 'Female', 'Jinan');
insert into customer (fullName, address, phone, age, gender, password) values ('Maudie Bottrell', 'Chisec', '+502 879 775 9343', 87, 'Female', 'Bogota');
insert into customer (fullName, address, phone, age, gender, password) values ('Kara-lynn Barrows', 'Padaimut', '+62 961 753 1578', 80, 'Female', 'Woodbridge');
insert into customer (fullName, address, phone, age, gender, password) values ('Erastus Vaines', 'Loma Bonita', '+52 309 647 2537', 54, 'Male', 'Misawa');
insert into customer (fullName, address, phone, age, gender, password) values ('Meagan McMennum', 'Palocabildo', '+57 546 499 3282', 84, 'Female', 'Centralia');
insert into customer (fullName, address, phone, age, gender, password) values ('Ronny Featherston', 'Guilin', '+86 451 473 7470', 76, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Ola Auden', 'Marādah', '+218 846 394 8932', 73, 'Female', 'Boca do Acre');
insert into customer (fullName, address, phone, age, gender, password) values ('Uri Cardenosa', 'Cikadu', '+62 555 242 9681', 64, 'Male', 'Hartley Bay');
insert into customer (fullName, address, phone, age, gender, password) values ('Hugo McIlenna', 'Dongzaogang', '+86 770 902 6243', 68, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Ardith Salzberger', 'Foso', '+233 274 584 5392', 87, 'Female', 'Pangoa');
insert into customer (fullName, address, phone, age, gender, password) values ('Obie Gerred', 'Donnybrook', '+353 162 420 2642', 51, 'Male', 'Álamos');
insert into customer (fullName, address, phone, age, gender, password) values ('Brianne Sket', 'União', '+55 424 200 3578', 40, 'Female', 'Baures');
insert into customer (fullName, address, phone, age, gender, password) values ('Lea Barrow', 'Arkhaía Kórinthos', '+30 118 189 2059', 84, 'Female', 'Lábrea');
insert into customer (fullName, address, phone, age, gender, password) values ('Gray Ccomini', 'Pingqiao', '+86 167 957 3228', 82, 'Female', 'Scribner');
insert into customer (fullName, address, phone, age, gender, password) values ('Eileen Elby', 'Vratsa', '+359 840 139 1591', 71, 'Female', 'Hrodna');
insert into customer (fullName, address, phone, age, gender, password) values ('Danit Foux', 'Boisbriand', '+1 278 988 6500', 70, 'Female', 'Hilton Head Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Hobard Flohard', 'Fuji', '+81 946 294 0071', 75, 'Male', 'Sandusky');
insert into customer (fullName, address, phone, age, gender, password) values ('Ashlin Cosham', 'Légua', '+351 328 686 2552', 25, 'Male', 'Hatay');
insert into customer (fullName, address, phone, age, gender, password) values ('Kaycee Pinney', 'Vicente Guerrero', '+52 882 594 2849', 28, 'Female', 'Bahía Solano');
insert into customer (fullName, address, phone, age, gender, password) values ('Shoshana Stapleford', 'Vanino', '+7 162 661 7569', 76, 'Female', 'Sylvester');
insert into customer (fullName, address, phone, age, gender, password) values ('Daveen Crowcombe', 'Zhuhong', '+86 271 312 4075', 33, 'Female', 'Kolda');
insert into customer (fullName, address, phone, age, gender, password) values ('Vincenty Whaites', 'Xuebu', '+86 814 425 0472', 73, 'Male', 'Wallal');
insert into customer (fullName, address, phone, age, gender, password) values ('Wit Confort', 'Zhenxi', '+86 422 505 1006', 93, 'Male', 'Fort Simpson');
insert into customer (fullName, address, phone, age, gender, password) values ('Freida Filipowicz', 'Penglai', '+86 626 891 3010', 53, 'Female', 'Grímsey');
insert into customer (fullName, address, phone, age, gender, password) values ('Dacia McLaggan', 'Villa Nueva', '+54 854 836 1946', 52, 'Female', 'Maroochydore');
insert into customer (fullName, address, phone, age, gender, password) values ('Cherie Langer', 'Sydney', '+61 966 103 5013', 18, 'Female', 'Vyrburg');
insert into customer (fullName, address, phone, age, gender, password) values ('Viole De Bellis', 'Hamburg', '+49 632 836 3531', 38, 'Female', 'Whitehorse');
insert into customer (fullName, address, phone, age, gender, password) values ('Andrea Staneland', 'Svay Rieng', '+855 468 559 3814', 88, 'Male', 'American River');
insert into customer (fullName, address, phone, age, gender, password) values ('Theobald Chinery', 'Tres Unidos', '+51 555 214 8538', 91, 'Male', 'Mulatupo');
insert into customer (fullName, address, phone, age, gender, password) values ('Carroll Wolvey', 'Daqiao', '+86 515 201 4515', 95, 'Female', 'Ouvéa');
insert into customer (fullName, address, phone, age, gender, password) values ('Alexander Gibbard', 'Zapod', '+355 362 546 7032', 52, 'Male', 'Ossima');
insert into customer (fullName, address, phone, age, gender, password) values ('Gayle Moverley', 'Borlänge', '+46 545 970 4152', 49, 'Female', 'Mexicali');
insert into customer (fullName, address, phone, age, gender, password) values ('Hillyer Harber', 'Baiqiao', '+86 608 365 5545', 75, 'Male', 'Vatry');
insert into customer (fullName, address, phone, age, gender, password) values ('Marco Arundell', 'Almeria', '+34 835 852 3536', 98, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Vinnie Paute', 'Gävle', '+46 656 735 8401', 21, 'Female', 'Marco Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Quintin Castiglio', 'Jianrao', '+86 436 917 7719', 48, 'Male', 'Hamilton');
insert into customer (fullName, address, phone, age, gender, password) values ('Briana Roly', 'Fort Wayne', '+1 260 335 2650', 59, 'Female', 'Governador Valadares');
insert into customer (fullName, address, phone, age, gender, password) values ('Jamie Dudin', 'San Buenaventura', '+51 381 960 7936', 64, 'Male', 'Datadawai-Borneo Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Graeme Corfield', 'Wootton', '+44 534 808 3158', 77, 'Male', 'Leribe');
insert into customer (fullName, address, phone, age, gender, password) values ('Loren Northage', 'Longquan', '+86 613 673 4891', 19, 'Female', 'Nashua');
insert into customer (fullName, address, phone, age, gender, password) values ('Gibbie Ivanchin', 'Calibungan', '+63 536 205 9630', 91, 'Male', 'Wannukandi');
insert into customer (fullName, address, phone, age, gender, password) values ('Stepha Bodicum', 'Ballina', '+353 647 966 6288', 62, 'Female', 'Block Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Georgy Doward', 'Göteborg', '+46 475 488 6960', 20, 'Male', 'Eskilstuna');
insert into customer (fullName, address, phone, age, gender, password) values ('Christina Lanning', 'Novyye Kuz’minki', '+7 208 151 2694', 49, 'Female', 'Duxford');
insert into customer (fullName, address, phone, age, gender, password) values ('Gabriello Fedorski', 'Tuzhai', '+86 600 426 9801', 85, 'Male', 'Allentown');
insert into customer (fullName, address, phone, age, gender, password) values ('Rodge Fleg', 'Kyllíni', '+30 877 322 6628', 40, 'Male', 'Dinangat');
insert into customer (fullName, address, phone, age, gender, password) values ('Algernon Cordner', 'Xiongzhang', '+86 918 137 4232', 73, 'Male', 'Elim');
insert into customer (fullName, address, phone, age, gender, password) values ('Arri Roiz', 'Longtang', '+86 552 432 8492', 24, 'Male', 'Kigoma');
insert into customer (fullName, address, phone, age, gender, password) values ('Piotr Nathon', 'Kyperoúnta', '+357 936 903 3163', 50, 'Male', 'Bonn');
insert into customer (fullName, address, phone, age, gender, password) values ('Berkly Fisbey', 'Lyamino', '+7 952 483 7608', 96, 'Male', 'Chernivtsi');
insert into customer (fullName, address, phone, age, gender, password) values ('Harlen Antcliff', 'Mŭglizh', '+359 704 310 3362', 60, 'Male', 'Lorient/Lann/Bihoué');
insert into customer (fullName, address, phone, age, gender, password) values ('Marya Erni', 'Çepan', '+355 730 877 6846', 63, 'Female', 'Merluna');
insert into customer (fullName, address, phone, age, gender, password) values ('Nona Fucher', 'Caofang', '+86 141 592 5997', 58, 'Female', 'Manila');
insert into customer (fullName, address, phone, age, gender, password) values ('Lolita Plet', 'Lutun', '+86 384 574 0381', 19, 'Female', 'Mora');
insert into customer (fullName, address, phone, age, gender, password) values ('Derrek Cody', 'Shaheying', '+86 267 852 2323', 61, 'Male', 'Vitória Da Conquista');
insert into customer (fullName, address, phone, age, gender, password) values ('Henrieta Balhatchet', 'Ibusuki', '+81 113 598 9178', 99, 'Female', 'Ramagundam');
insert into customer (fullName, address, phone, age, gender, password) values ('Lydie Croson', 'Bokat', '+62 585 658 0761', 34, 'Female', 'Erechim');
insert into customer (fullName, address, phone, age, gender, password) values ('Aldis Maccari', 'Bayt ‘Anān', '+970 980 587 6712', 22, 'Male', 'London');
insert into customer (fullName, address, phone, age, gender, password) values ('Cash Gricks', 'Tiandu', '+86 580 407 3481', 34, 'Male', 'Lakefield National Park');
insert into customer (fullName, address, phone, age, gender, password) values ('Dorrie Woolvin', 'Tuwiri Wetan', '+62 448 307 8975', 23, 'Female', 'Shiringayoc');
insert into customer (fullName, address, phone, age, gender, password) values ('Daron Kale', 'San Andrés', '+502 938 814 5077', 70, 'Male', 'Rolla/Vichy');
insert into customer (fullName, address, phone, age, gender, password) values ('Dasya Claige', 'Palmar de Varela', '+57 345 391 7588', 64, 'Female', 'Lake Rudolf');
insert into customer (fullName, address, phone, age, gender, password) values ('Ludovico Gillett', 'Chengui', '+86 970 655 7783', 20, 'Male', 'Artesia');
insert into customer (fullName, address, phone, age, gender, password) values ('Dene Haddow', 'Aykol', '+86 702 282 3048', 54, 'Male', 'Bangkok');
insert into customer (fullName, address, phone, age, gender, password) values ('Hildagarde Lorens', 'Sampués', '+57 786 835 8067', 84, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Camala Starsmeare', 'Grojec', '+48 432 289 8755', 61, 'Female', 'Tabiteuea South');
insert into customer (fullName, address, phone, age, gender, password) values ('Lauryn Renbold', 'Matur', '+62 238 322 7776', 30, 'Female', 'Bournemouth');
insert into customer (fullName, address, phone, age, gender, password) values ('Naomi Burnitt', 'Wuyang', '+86 282 651 5210', 68, 'Female', 'Pica');
insert into customer (fullName, address, phone, age, gender, password) values ('Woody Braisher', 'Pakel', '+62 386 210 5615', 26, 'Male', 'Quezaltenango');
insert into customer (fullName, address, phone, age, gender, password) values ('Paulo Henrot', 'San Antonio de Los Altos', '+58 239 892 7942', 41, 'Male', 'Magdeburg');
insert into customer (fullName, address, phone, age, gender, password) values ('Hestia Wrist', 'Leiria', '+351 752 263 2652', 39, 'Female', 'Solomon');
insert into customer (fullName, address, phone, age, gender, password) values ('Hendrick Lawlance', 'Lieyu', '+86 488 125 2518', 78, 'Male', 'Garça');
insert into customer (fullName, address, phone, age, gender, password) values ('Blancha Seadon', 'Xagmakajor', '+86 462 304 4104', 93, 'Female', 'Hachijojima');
insert into customer (fullName, address, phone, age, gender, password) values ('Andree Karim', 'Bile', '+380 126 737 2064', 48, 'Female', 'Miranda Downs');
insert into customer (fullName, address, phone, age, gender, password) values ('Sunny Bedingfield', 'Wulong', '+86 996 608 9295', 59, 'Female', 'Jamestown');
insert into customer (fullName, address, phone, age, gender, password) values ('Elisha Robertis', 'Yala', '+66 817 343 2684', 30, 'Male', 'Wuxi');
insert into customer (fullName, address, phone, age, gender, password) values ('Noelle Tidman', 'Debrecen', '+36 280 817 4695', 33, 'Female', 'Phan Rang');
insert into customer (fullName, address, phone, age, gender, password) values ('Suzy Pantin', 'Suyo', '+63 251 338 3012', 27, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Tersina MacAdam', 'Qinggis Han', '+86 942 952 6725', 64, 'Female', 'Redcliffe');
insert into customer (fullName, address, phone, age, gender, password) values ('Robers Mahoney', 'Yazd', '+98 657 798 9959', 32, 'Male', 'Valença');
insert into customer (fullName, address, phone, age, gender, password) values ('Myrtice Rolles', 'Dayr al Ghuşūn', '+970 499 858 2341', 66, 'Female', 'Beloretsk');
insert into customer (fullName, address, phone, age, gender, password) values ('Mohandis Rottgers', 'Rust’avi', '+995 528 421 4776', 59, 'Male', 'Ringi Cove');
insert into customer (fullName, address, phone, age, gender, password) values ('Gerome Aleksankov', 'Chhāgalnāiya', '+880 280 659 2205', 63, 'Male', 'Nefteyugansk');
insert into customer (fullName, address, phone, age, gender, password) values ('Mike Beincken', 'Cala', '+27 743 675 6164', 25, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Jaclin Shottin', 'Slavgorod', '+7 936 697 7017', 73, 'Female', 'Ormoc City');
insert into customer (fullName, address, phone, age, gender, password) values ('Halette Cromblehome', 'Bogorame', '+62 660 546 0486', 25, 'Female', 'Bragança Paulista');
insert into customer (fullName, address, phone, age, gender, password) values ('Amye Dallinder', 'Reykjanesbær', '+354 307 918 9886', 75, 'Female', 'Aishalton');
insert into customer (fullName, address, phone, age, gender, password) values ('Freida MacClancey', 'Pokrovo-Prigorodnoye', '+7 159 438 8431', 67, 'Female', 'Brevig Mission');
insert into customer (fullName, address, phone, age, gender, password) values ('Padriac Garley', 'Siedlce', '+48 605 805 6443', 63, 'Male', 'Langebaanweg');
insert into customer (fullName, address, phone, age, gender, password) values ('Derward Ruprich', 'Yongqin', '+86 629 520 6951', 75, 'Male', 'Tablas Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Karrah Beekman', 'Ancenis', '+33 937 567 5595', 97, 'Female', 'Milan');
insert into customer (fullName, address, phone, age, gender, password) values ('Charley Skipsey', 'Zheleznogorsk', '+7 676 217 1933', 22, 'Male', 'Munich');
insert into customer (fullName, address, phone, age, gender, password) values ('Gar Rameau', 'Österbybruk', '+46 399 594 7680', 78, 'Male', 'Bokpyinn');
insert into customer (fullName, address, phone, age, gender, password) values ('Else Maus', 'Venda Nova', '+351 294 980 0255', 26, 'Female', 'Tissamaharama');
insert into customer (fullName, address, phone, age, gender, password) values ('Chandler Eskell', 'Gujō', '+81 156 205 3677', 67, 'Male', 'Moengo');
insert into customer (fullName, address, phone, age, gender, password) values ('Phillip Daveren', 'Changshan', '+86 800 961 2221', 82, 'Male', 'Pune');
insert into customer (fullName, address, phone, age, gender, password) values ('Ariadne Stave', 'Masindi Port', '+256 864 677 4237', 53, 'Female', 'Kudahuvadhoo');
insert into customer (fullName, address, phone, age, gender, password) values ('Guenevere Sainer', 'Duas Igrejas', '+351 412 250 7022', 39, 'Female', 'Bay City');
insert into customer (fullName, address, phone, age, gender, password) values ('Adele Glackin', 'Kyaukse', '+95 263 382 7788', 49, 'Female', 'São Miguel Arcanjo');
insert into customer (fullName, address, phone, age, gender, password) values ('Sibley Adanet', 'Luhanka', '+358 242 313 1648', 51, 'Female', 'Islip');
insert into customer (fullName, address, phone, age, gender, password) values ('Artemas Lighten', 'Karabash', '+7 234 721 2569', 72, 'Male', 'Laredo');
insert into customer (fullName, address, phone, age, gender, password) values ('Efren Storks', 'Binjai', '+62 375 782 8288', 95, 'Male', 'Mainoru');
insert into customer (fullName, address, phone, age, gender, password) values ('Berkie Vanyutin', 'Ryjewo', '+48 874 240 0249', 32, 'Male', 'Salvador');
insert into customer (fullName, address, phone, age, gender, password) values ('Cris Eby', 'Fornos', '+351 285 145 2290', 20, 'Male', 'Kolombangara Island');
insert into customer (fullName, address, phone, age, gender, password) values ('Guillemette Doolan', 'Duwakkandung', '+62 482 194 0196', 85, 'Female', 'Miranda Downs');
insert into customer (fullName, address, phone, age, gender, password) values ('Giles Lawler', 'Na Wa', '+66 945 650 1121', 31, 'Male', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Hilary Prout', 'Świnna', '+48 298 506 2263', 41, 'Male', 'Mangla');
insert into customer (fullName, address, phone, age, gender, password) values ('Granthem Stapels', 'Tamamura', '+81 943 793 3057', 70, 'Male', 'Leshukonskoye');
insert into customer (fullName, address, phone, age, gender, password) values ('Geoffrey Geaves', 'Springfield', '+1 217 875 1534', 95, 'Male', 'Mbuji Mayi');
insert into customer (fullName, address, phone, age, gender, password) values ('Agatha Kinch', 'Jitan', '+86 651 254 3172', 94, 'Female', 'Koulamoutou');
insert into customer (fullName, address, phone, age, gender, password) values ('Alikee Saltrese', 'Gorna Oryakhovitsa', '+359 298 280 8922', 37, 'Female', 'Sechelt');
insert into customer (fullName, address, phone, age, gender, password) values ('Clerissa MacAirt', 'Bromma', '+46 134 836 1030', 78, 'Female', 'Sedalia');
insert into customer (fullName, address, phone, age, gender, password) values ('Tabbie Duffer', 'Stonewall', '+1 344 550 8528', 43, 'Female', 'Halifax');
insert into customer (fullName, address, phone, age, gender, password) values ('Thaxter Korda', 'Qozonketkan', '+998 712 905 1964', 58, 'Male', 'Tichitt');
insert into customer (fullName, address, phone, age, gender, password) values ('Rodolphe Merigot', 'Kubangeceng', '+62 681 853 1053', 44, 'Male', 'Vojens');
insert into customer (fullName, address, phone, age, gender, password) values ('Delora Sancto', 'Matanzas', '+53 447 832 6409', 71, 'Female', 'Hong Kong');
insert into customer (fullName, address, phone, age, gender, password) values ('Dominique Follows', 'Uyen Hung', '+84 361 640 1117', 61, 'Female', 'Red Devil');
insert into customer (fullName, address, phone, age, gender, password) values ('Drugi Ellen', 'Nggesa', '+62 594 599 0911', 97, 'Male', 'Tupelo');
insert into customer (fullName, address, phone, age, gender, password) values ('Dusty Burgett', 'Burnside', '+44 856 218 5031', 44, 'Female', 'Ålesund');
insert into customer (fullName, address, phone, age, gender, password) values ('Dru Casterot', 'Manzurka', '+7 932 248 5647', 46, 'Male', 'Freetown');
insert into customer (fullName, address, phone, age, gender, password) values ('Andie Lundie', 'Murtajih', '+62 183 566 7536', 71, 'Female', 'Gardez');
insert into customer (fullName, address, phone, age, gender, password) values ('Kurt Comberbach', 'Zvëzdnyy', '+7 462 999 5697', 99, 'Male', 'Juazeiro Do Norte');
insert into customer (fullName, address, phone, age, gender, password) values ('Rhett Matczak', 'Doug An', '+84 483 655 5742', 41, 'Male', 'Marshall');
insert into customer (fullName, address, phone, age, gender, password) values ('Helen Fiander', 'Mende', '+33 516 191 6420', 76, 'Female', 'Fort Indiantown Gap(Annville)');
insert into customer (fullName, address, phone, age, gender, password) values ('Orin O''Cosgra', 'Santa Valha', '+351 557 416 9644', 83, 'Male', 'Myvatn');
insert into customer (fullName, address, phone, age, gender, password) values ('Bax Langforth', 'Horní Čermná', '+420 978 996 3423', 27, 'Male', 'Thompson Falls');
insert into customer (fullName, address, phone, age, gender, password) values ('Moshe Lankham', 'Kudang', '+62 335 467 7807', 52, 'Male', 'Bozoum');
insert into customer (fullName, address, phone, age, gender, password) values ('Emilio Arnatt', 'Qianjiang', '+86 816 437 6640', 41, 'Male', 'Lipetsk');
insert into customer (fullName, address, phone, age, gender, password) values ('Bibby de Verson', 'Bangkle', '+62 137 209 8296', 41, 'Female', 'Salekhard');
insert into customer (fullName, address, phone, age, gender, password) values ('Zuzana Oles', 'Jinshiqiao', '+86 582 811 5899', 32, 'Female', 'Ouhasdo');
insert into customer (fullName, address, phone, age, gender, password) values ('Barbee Van der Daal', 'Motala', '+46 655 499 9363', 89, 'Female', 'Ravenna');
insert into customer (fullName, address, phone, age, gender, password) values ('Catlee McNally', 'Kaliprak', '+62 587 396 7876', 43, 'Female', 'Currais Novos');
insert into customer (fullName, address, phone, age, gender, password) values ('Judie Johns', 'Bailizhou', '+86 923 561 8417', 67, 'Female', 'Dongying');
insert into customer (fullName, address, phone, age, gender, password) values ('Magdaia Revance', 'Dampek', '+62 458 840 8293', 21, 'Female', 'Miami');
insert into customer (fullName, address, phone, age, gender, password) values ('Kissee MacNamee', 'Kuala Lumpur', '+60 717 607 3527', 80, 'Female', 'Goiânia');
insert into customer (fullName, address, phone, age, gender, password) values ('Modesta Brittles', 'Hamm', '+49 586 309 6680', 88, 'Female', 'Sege');
insert into customer (fullName, address, phone, age, gender, password) values ('Marlane Smoughton', 'Caen', '+33 127 124 2284', 49, 'Female', 'Nanjing');
insert into customer (fullName, address, phone, age, gender, password) values ('Sheff Lyffe', 'Yukuhashi', '+81 979 724 0970', 19, 'Male', 'Jordan');
insert into customer (fullName, address, phone, age, gender, password) values ('Kesley Agent', 'Eksjö', '+46 924 697 2102', 35, 'Female', 'Lushoto');
insert into customer (fullName, address, phone, age, gender, password) values ('Estevan Dulin', 'Caballococha', '+51 329 426 4188', 81, 'Male', 'Fulleborn');
insert into customer (fullName, address, phone, age, gender, password) values ('Fonsie Slavin', 'Puyang', '+86 328 128 6079', 20, 'Male', 'Biała Podlaska');
insert into customer (fullName, address, phone, age, gender, password) values ('Seana Ferandez', 'Longchi', '+86 138 318 2463', 45, 'Female', 'Khulna');
